<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CQRS.DataAccess\CQRS.DataAccess.csproj" />
      <ProjectReference Include="..\CQRS.Data\CQRS.Data.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MongoDB.Bson" Version="3.4.3" />
    </ItemGroup>

</Project>
