<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>71f2c0c6-a22b-4ed6-9213-2612d74a0c7a</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CQRS.DataAccess\CQRS.DataAccess.csproj" />
      <ProjectReference Include="..\CQRS.Queries\CQRS.Queries.csproj" />
      <ProjectReference Include="..\CQRS.Commands\CQRS.Commands.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

</Project>
